### ISSUE TITLE
Better style sheet documentation for model types

### ISSUE THREAD

**Issue by rwilbur** [gaphor/gaphor#1172]
### Is your feature request related to a problem?
It is very hard to edit the style of a diagram because model types are not documented. Currently the only way to figure out how to change the style of certain objects is to guess what the name is or to look through the source which adds a large barrier to new people using it.

### Describe the solution you'd like
The documentation for the style sheets should include a list of all the model types that can be added into the diagram.

**Comment by amolenaar** [comment]
Hi @rwilbur,

Thanks for the feedback.

I think adding a list of all possible model types is a bit hard, since there are so many. Adding a shortlist is a plan.

Can you explain a little what you're using Gaphor for, and what you want to do with a custom style sheet? Just to provide me some context :smiley:

**Comment by amolenaar** [comment]
Hi @rwilbur, I added a section to the docs: https://gaphor.readthedocs.io/en/latest/style_sheets.html#working-with-model-elements. Is this what you're after?

**Comment by rwilbur** [comment]
That was fast! That is exactly what I was looking for! I'm using graphor for making some software architecture diagrams for some embedded systems. I am using the custom style sheet to try to color code things in it.

**Comment by amolenaar** [comment]
Awesome! I'm glad I could help :smiley:
