### ISSUE TITLE
Static main method with array parameter not set.

### ISSUE THREAD

**Issue by jcbritobr** [gaphor/gaphor#1185]
### Describe the bug
When trying to put a main static method with a string array in class, gaphor change it to simple variable

### To Reproduce
1 - Seclect a class
2 - Create a method with static mark
3 - Set "+ main(args: String[]): void"

### Expected behavior
A method with + main(args: String[]): void in class

### Screenshots
![image](https://user-images.githubusercontent.com/6579862/145098508-98961e70-3dc7-42ce-a6d9-6b986f702966.png)

### OS
Windows

### Version
Version of Gaphor: 2.7.1

**Comment by amolenaar** [comment]
Hi,

The official syntax would be `main(args: String[*])`. The items between square brackets is the multiplicity. I can see this is confusing, since in most programming languages `[]` denotes an array of unspecified size. It would probably be better to interpret `[]` as `[*]`. What do you think?

See also https://www.uml-diagrams.org/operation.html.

**Comment by jcbritobr** [comment]
> Hi,
> 
> The official syntax would be `main(args: String[*])`. The items between square brackets is the multiplicity. I can see this is confusing, since in most programming languages `[]` denotes an array of unspecified size. It would probably be better to interpret `[]` as `[*]`. What do you think?
> 
> See also https://www.uml-diagrams.org/operation.html.

Agreed and it works. I will close the issue here. :)

**Comment by amolenaar** [comment]
Never the less. I think Gaphor can help us by interpreting `[]` as `[*]`.
