### ISSUE TITLE
database diagrams

### ISSUE THREAD

**Issue by GeorgeSalu** [gaphor/gaphor#1235]
are there plans to include database diagrams?

**Comment by danyeaw** [comment]
Hi @GeorgeSalu, thanks for the idea. What type of database diagram nomenclature or notation would you like to see? It is possible to model database design in UML:
https://stackoverflow.com/questions/21358774/database-design-using-uml-class-diagram
https://sparxsystems.com/downloads/whitepapers/Database_Modeling_In_UML.pdf

Also in C4 model, a Container can represent a database, and we support that notation.

**Comment by GeorgeSalu** [comment]
it would be great to be able to have Crow Foot notation https://vertabelo.com/blog/crow-s-foot-notation/, thanks for the great work on gaphor we have been using it for uml

**Comment by danyeaw** [comment]
So would we support a separate Database profile that is built on top of UML for this? Then we can support a SQL or Database diagram and do things like allow the user to show the Crow's Foot notation instead of a normal association?

This is very much out of my knowledge area, so we probably need someone who is an expert to get involved and help define how this would work and maybe even take the lead on creating the profile itself.

**Comment by GeorgeSalu** [comment]
I think you could have a database profile that supports this notation, I think what would be most needed today is support for crows foot notation connectors because entities could use today's class symbol from the class diagram

**Comment by danyeaw** [comment]
So maybe first: create a new diagram type that changes the look so that associations use crow's feet notation?

**Comment by GeorgeSalu** [comment]
yes, i think it's a good idea to create a new type of diagram even to keep a good organization

**Comment by kmare** [comment]
Hi, this is a feature I'd really love to see implemented in Gaphor.
Is it still planned or under consideration? Do you believe it would be hard to implement by someone not familiar with the code base of Gaphor?
Thank you for the great software btw!

**Comment by amolenaar** [comment]
Hi @kmare,

Thanks for your response. Personally, this is low on my priority list. I think everything you want from database diagrams can be done with UML classes and associations just as well (please correct me if I'm wrong).

Would it be hard to implement? I think not, since it's basically adaptations to already existing elements. You can choose to reuse the UML metamodel or create a specific one.

Having that said, I think it's really useful to have a fresh view on the code. We've been developing it for years, so i expect we're a bit biased :wink:.

We have a page addressing modeling languages at https://gaphor.readthedocs.io/en/latest/modeling_language.html. It may seem a bit overwhelming, but all bits can be implemented separately.

**Comment by amolenaar** [comment]
I'll close this issue. If the subject comes up again we can reopen it.
