### ISSUE TITLE
Delete model element does not work

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1247]
### Describe the bug
Existing model elements cannot be removed from the model.

### To Reproduce
1. Create a new project (generic)
2. Add a class
3. Right mouse click in the navigation, delete is disabled

### Expected behavior
I expect to remove any element from the model

### OS
- [X] Linux
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: git latest

**Comment by amolenaar** [comment]
This behavior was intentional: you can not remove an item that's still part of a diagram.

With the recent changes and the ability to disable the "Remove Unused Elements" behavior, we have to address this as well.

The simple solution is to just allow deletion. This will automatically trigger the deletion of element presentations in diagrams.
