### ISSUE TITLE
Association end can be deleted when shown as Property in diagram

### ISSUE THREAD

**Issue by h8672** [gaphor/gaphor#1259]
### Describe the bug
Pulling head or tail element from arrow draws a new element with "< element text >: < target element >" text in it.

Deleting it in diagram removes it from navigation and arrow type changes.

If the arrow element has text in the element, that head or tail element is also removed from the arrow.

I presume it should continue to exist in tree view with that arrow type especially if it has name or description in it.

### To Reproduce

1. Draw arrow in diagram.
2. Add head and tail text (optional, but gives better visibility).
3. Drag element from that arrow in project tree to any diagram.
4. Delete the dragged element.
- Arrow element loses the element you dragged and deleted.
5. Delete the arrow.
- Arrow doesn't disappear.
6. Delete other arrow element the same way as earlier one.
7. Delete the arrow.
- Arrow is deleted now.

### Expected behavior
1. You couldn't drag arrow head or tail elements.
2. If drag is intended, deleting it wouldn't mutate the arrow.
3. You can delete arrow no matter how many elements it contains.

### OS
- [x] Linux (Pop OS 21.10)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.7.1 (flatpak)

### Additional information
Would be cool to change base arrow / line type in properties by adding line text or arrows head / tail elements.

**Comment by amolenaar** [comment]
Hi @h8672, what type of arrow are you referring to? An _association_?

**Comment by h8672** [comment]
Yes, **association** was the one I tested with.

**Comment by amolenaar** [comment]
I tried to follow your directions

* I create 2 classes (`A` and `B`)
* Create an Association between those two classes
* make both ends _navigable_ (now the arrow heads appear)
* Drag class `A` from the tree view into the diagram
* Delete that very element.
* Class `A` and `B` and the association stay as is.
* Delete the other `A` element -- the element is now also removed from the tree view.
* Now the arrow heads disappear: the association line does not have both ends connected. For an association to exist (in the model), it needs to be connected on both ends.

Not sure if this is also what happened to you. Point is that, in order to keep the model consistent, associations (and any relationship for that matter) are only created in the model when both ends of a line are connected. If arrows are created on associations depend on the state of the model.

**Comment by h8672** [comment]
Oh adding navigable does the same... but with those head and tail elements are moved to under those classes in tree view instead of < relationships > Arrow
Well... still couldn't delete the association when I removed C part of those, needed to delete D element.
Same vice versa, D, cant remove association, and then C, can remove arrow.
https://user-images.githubusercontent.com/8805540/148383018-6b072ad0-c2cb-4682-9ff8-7259876348ac.mp4

**Comment by amolenaar** [comment]
No, the video doesn't upload. You can upload it to our chat channel maybe (https://gaphor.org/discuss.html) or sent me directly at gaphor@gmail.com.

**Comment by h8672** [comment]
@amolenaar Sent it in email.

**Comment by amolenaar** [comment]
@h8672 Thanks. The small video made it clear to me what's happening. A really nice find! Thanks a lot.

You have 2 classes connected via an association. Then one of the association end properties is dragged into the diagram and deleted.
By removing it the last appearance of that property is removed, hence the property is removed. But this leaves the association in an invalid state, since it's missing one association end at that moment.

**Comment by amolenaar** [comment]
I fixed it for 2.8.0. the next version should be released soon.

Again, thanks for reporting this issue :clap:
