### ISSUE TITLE
Union types

### ISSUE THREAD

**Issue by dk-zero-cool** [gaphor/gaphor#1563]
Hi. 

While trying to make a diagram of a small PHP project, to get a better overview, I have had some problems when wanting to define union types. It does not really like characters like `|` being used. The nullable character `?` is not popular either, but can be replaced with `type|null` at least, if that was allowed. You can force it via the left pane by manually editing the type, but some times this screws up things like `in` and `inout`, or just removes the whole type. 

I know that UML is more designed to represent things like this in a more Java like fashion, by adding multiple methods with different parameters, but many languages also implies nullable, which must be declared explicitly with PHP. Adding `method(arg: null)` or `method(): null` would look weird.

**Comment by amolenaar** [comment]
Hi @dk-zero-cool,

Thank you for your feedback. UML does not have the concept of union types, as far as I know. However, in Python we have those as well. It would make sense to support those to some extend (textual). I agree that nullable (`?`) would also make sense, since it's also used in languages like Ruby and Kotlin.

@all-contributors Add @dk-zero-cool for ideas.
