### ISSUE TITLE
If I implement UPDM, I want to know how I can do it.

### ISSUE THREAD

**Issue by Iyetux** [gaphor/gaphor#1610]
I'm a novice. I feel I can't start by reading doc. I want to know where to start if I want to realize UPDM?

**Comment by danyeaw** [comment]
Hi @Iyetux, I'm less familiar with UPDM, but I understand it is a combination of SysML and SoaML. We don't support UPDM currently as a profile, is that what you are requesting?

**Comment by Iyetux** [comment]
@danyeaw  thanks for you replay!
Gaphor is a great design. Standing on the shoulders of giants, I want to try to realize my ideas. However, the reality makes me stop.

**Comment by danyeaw** [comment]
Hi @Iyetux, since this doesn't sound like a bug or a feature request, I am going to go ahead and close this. If you have specific questions, you can make use of our [Discussion](https://github.com/gaphor/gaphor/discussions) or come chat with us on [Element](https://app.element.io/#/room/#gaphor_Lobby:gitter.im).
