### ISSUE TITLE
State Machine diagrams: composite states and choice states (and other missing elements)

### ISSUE THREAD

**Issue by vanem** [gaphor/gaphor#1654]
The editor has a great look@feel, but I'm mostly interested in UML (Hierarchical) State Machines. The most important elements missing would be Composite States (otherwise you are limited to very simple behaviors ) and to a lesser extent the Choice Pseudostate.
Other elements are missing like: adding multiple activities, custom activities (also called "internal self transitions"),  Regions, Join, Fork

**Comment by amolenaar** [comment]
Hi @vanem,

Thank you for your feedback. For the most part I've been focusing on activity diagrams (Actions). State machines could use some love :smile:.

A quick check makes me assume pseudo states can easily be added to [PseudostateItem](https://github.com/gaphor/gaphor/blob/main/gaphor/UML/states/pseudostates.py) and the [toolbox](https://github.com/gaphor/gaphor/blob/main/gaphor/UML/states/statestoolbox.py). Composite states are probably a bit more work, mostly allow states to be nested.

Can you help with implementing? It will be very much appreciated.

**Comment by vanem** [comment]
Unfortunately I have no UI /Gtk experience (and dealing with 2 jobs atm). https://github.com/DLR-RM/RAFCON builds on gaphas (but their interpretation of HFSMs is very different from UML), perhaps someone could find some useful inspiration in their repo.

**Comment by amolenaar** [comment]
Okay, PR for pseudostates is up.

In order to have a complete story for state machines we still need:

- [ ] Allow multiple regions in a state machine
- [ ] Allow composite states. E.i. a region in a state that can contain states and transitions.

Having multiple regions in a state (machine) poses an issue similar to #1014: when resizing, adding and removing regions the relation between the state and it's (visually) containing region should be maintained.

**Comment by amolenaar** [comment]
State machines:

![image](https://user-images.githubusercontent.com/96249/185649270-94d64421-b395-41ab-b2d1-e87bf4977b1c.png)

**Comment by amolenaar** [comment]
Implemented by #1662 and #1666.
