### ISSUE TITLE
Win64 2.11.0 download has FileRepMalware

### ISSUE THREAD

**Issue by Musicman5423** [gaphor/gaphor#1674]
### Describe the bug
Downloaded the Windows 2.11.0 installer.  Avast quarantined it because it found FileRepMalware [Misc]

### To Reproduce
Download the installer.  Scan w/Avast.

### Screenshots
![image](https://user-images.githubusercontent.com/111323454/184756409-607d51b9-0095-4e0d-9510-80a9402331ab.png)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.11.0

**Comment by danyeaw** [comment]
Hi @Musicman5423 thanks for submitting this issue!

I realize this is a bad user experience. Unfortunately, there is nothing we can personally do to fix this. I would recommend submitting this as a false positive to the antivirus company, and hopefully they will improve their product to not detect legitimately packaged and signed software as a virus or malware.

**Comment by SebCanet** [comment]
Sorry to add information on an old problem, but the problem is wider. I've sent "gaphor-exe.exe" to VirusTotal: [https://www.virustotal.com/gui/file/aebf7a316b9fb3c997dfe4fbcdcf91830c3828f05d64ae0616bf4d486986adf1](https://www.virustotal.com/gui/file/aebf7a316b9fb3c997dfe4fbcdcf91830c3828f05d64ae0616bf4d486986adf1)

Maybe you should contact this companies to ask them change it.
