### ISSUE TITLE
Snaps for Gaphor 

### ISSUE THREAD

**Issue by Saphyel** [gaphor/gaphor#1776]
Ubuntu comes with snaps and most of the gnome things comes with snaps so I think will be great to have it. Canonical released a pdf about using Gnome extensions https://blogs.gnome.org/hellsworth/files/2019/11/GNOME-extensions-for-desktop-apps.pdf

I'm happy to help if needed.

**Comment by danyeaw** [comment]
Hi @Saphyel, we already have our hands full supporting Flatpak, AppImage, macOS, and Windows. If you would like to implement support for Snaps and help us maintain it, we would be open to it. We are all for supporting more formats because that connects us with more potential users, but we need contributors to help.

**Comment by danyeaw** [comment]
Hi @Saphyel, are you interested in contributing and supporting snaps?

**Comment by Saphyel** [comment]
@danyeaw yes, I'm working on it. I can raise a PR with my progress tonight

**Comment by vanillajonathan** [comment]
@Saphyel how is your progress going on this?

**Comment by danyeaw** [comment]
Another negative of us supporting Snaps is the Snap Store itself is commercially operated by Canonical, and it is not OSS.

**Comment by danyeaw** [comment]
Hey @Saphyel, thanks for submitting this idea. We recently dropped AppImage support, and we are going to focus our Linux packaging efforts on Flatpak. If someone wants to package Gaphor with Snap or another packaging format, that is great, but we aren't interested in maintaining that as part of Gaphor at this time.

**Comment by anrouxel** [comment]
Hello
I would like to add gaphor support to snapcraft as a community service. I would just like to know if you have the gaphor name for snapcraft so that I can publish it.
Here is the repository containing the snapcraft.yaml file for gaphor.
[https://github.com/anrouxel/gaphor-snapcraft](https://github.com/anrouxel/gaphor-snapcraft)

For update management, a GitHub action is run daily in the gaphor-snapcraft repository to check whether the gaphor repository has a new update. If there's a new version, then it creates the Snap and publishes it to the Edge branch of Snapcraft and then runs tests and screenshots of the application. If everything's OK, then I publish it to the stable branch. So if there are no errors, the deadline is 24 hours after the release in the gaphor repository.

Best Regards
Antonin Rouxel
