### ISSUE TITLE
Improve welcome experience

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1879]
In the current stable version, opening the app initially opens just this dialog:

![image](https://user-images.githubusercontent.com/1908896/204263761-b2e0fecc-3b62-4cf5-a574-749a5f98b018.png)

This is not ideal, because it puts one extra step in front of the actual app opening, which feels like a hurdle. I'd recommend immediately opening the real app window, and either integrating the welcome experience into the main window (like e.g. Builder does on its new tab page), or having the welcome dialog on top of the main window.

The dialog itself could also be improved:
- There is no context about the options other than the names and logos, which doesn't feel approachable. A description for each of the options would be helpful to make the choice easier, perhaps with example use cases.
- The logos are quite prominent, which isn't great since some of them are a bit ugly and they're stylistically inconsistent between each other. It might help to have them all inside white circles or something, to make them look more uniform. Arranging them as a list rather than a grid, with smaller icons, could also help.
- The blue focus state feels off-style, we usually use semi-transparent text color for that
- The dialog feels a bit empty and top-heavy, I'd resize it and, depending on whether you go with list or grid, potentially center the content vertically

**Comment by amolenaar** [comment]
Hi @bertob,

Thanks a lot for your feedback!

I based this loosely on Builder. When I start it, it welcomes me with a "Open a Project" window. Once you have opened a model, it will show the previously opened models, instead of this new-model window. I miss a button to open a model from the file system, though.

The size is based on the recent-models (GNOME builder 3). I suppose we can put them all in one window, in a list and not have separate pages for existing and new models.

**Comment by amolenaar** [comment]
@bertob I did some work on the greeter. Instead of the blocks, it now shows the options for creating a new model from a template as a list, with the icon in front.

See #1892. Does this come close(r) to a visually appealing design?

**Comment by bertob** [comment]
Commented on the MR :)
