### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [gaphor/gaphor#2220]
### Describe the bug[
A clear and concise description of what the bug is.](https://hosted.weblate.org/projects/gaphor/gaphor-org-strings/#information)
says GPLv3-only,
whereas
https://github.com/gaphor/gaphor/blob/6fc70dd23982e8f79ff7d702f1c1cdeff881f1a3/_packaging/hook-pydot.py#L10
https://github.com/gaphor/gaphor/blob/dce5cc96221ecade5d98796df79672b22ddcfb28/_packaging/windows/win_installer.nsi#L6 and
https://github.com/gaphor/gaphor/blob/8b1ab16e4ca4768e8d49e7b6fb29dbd2598589a1/gaphor/ui/language-specs/gaphorcss.lang#L19
Say -or-later

Can be changed in https://hosted.weblate.org/settings/gaphor/gaphor-org-strings

I don't know what component that refers to, but might be good to get that sorted now if in error.
Strange that `.org strings` is different from `.org pages` I thought
https://hosted.weblate.org/projects/gaphor/#information

**Comment by danyeaw** [comment]
Hi @comradekingu, Gaphor itself is licensed at Apache 2 and the license is here:
https://github.com/gaphor/gaphor/blob/main/LICENSE.txt

Yes, there are a few files that we modified from other projects for our own use and the licenses of those files had to stay intact.

Our website which is what that Weblate component is referring to is located at https://github.com/gaphor/gaphor.github.io. It is licensed as GPL 3.0 and the license is here: https://github.com/gaphor/gaphor.github.io/blob/main/LICENSE.txt

We did have to split up gaphor.org strings and pages to separate translation components because they have different methods of doing the translation. The strings are using yaml files and the pages are using po files. This is due to a not being able to translate key parts of a static website except by injecting specific strings.

**Comment by comradekingu** [comment]
That distinction seems arbitrary to what constitutes "a work" in the copyright sense.
From my understanding the two are incompatible as a combination, but in the very least two of the same are compatible,
with "or later" allowing for the most flexibility.

Could it be better to go "or later" now for both of the website components, to make sure to avoid having to ask individual contributors later?

**Comment by danyeaw** [comment]
I think the license itself is GPL v3. The GPL then recommends in the How to Apply These Terms appendix of the license that we add the license to each source file with a short license header. It is in these headers where we would say optionally that it is licensed with GPL v3 or later. We aren't using these license headers, so the distinction of or later doesn't really apply.

However, I think I agree that in Weblate it would probably be better to select the license as GPL v3 or later, rather than GPL v3 only. I also understand that the Pages component said or later and the Strings component said only. I have updated the Strings component, so it says or later as well. Thanks for submitting the suggestion. :+1:
