### ISSUE TITLE
Ability to select interface language

### ISSUE THREAD

**Issue by flatrick** [gaphor/gaphor#2346]
### Is your feature request related to a problem?
When Gaphor selects the UI language, for those languages that aren't completely translated, it just doesn't look good. For some languages, there is also the risk of "false positives", i.e. that the word in English (that seems to be the fallback) might mean something else in the language that the UI is supposed to be showing.

Not everyone wants the program to be in their native language either, it is sometimes just easier sticking to English as most help found online will be in English for a lot of users.

### Describe the solution you'd like
Ability to select which language the UI is in.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by amolenaar** [comment]
Hi @flatrick, the UI language can be selected on system level. For example: I'm Dutch, but I use English as my UI language. This is picked up perfectly by Gaphor.

If you want a different language, you can also set the `LANG` environment variable before starting Gaphor.

See also #2162

To solve partially translated text, the best way is to translate the remaining terms.
Having that said, we could use some help with [translating Gaphor](https://hosted.weblate.org/projects/gaphor/gaphor/) :).

**Comment by flatrick** [comment]
Setting env-variables before running the application isn't very user-friendly so I still think this should be an exposed setting from the running application.

And system-language is good to use as a suggestion for ui-language, but it isn't always the desired choice.  
There are plenty of people who can't change system language because of other apps having a similar requirement for a specific system language, or where their IT department don't allow changing these settings.

**Comment by danyeaw** [comment]
@flatrick Thanks for the suggestion!

We are aiming to follow the [GNOME Human Interface Guidelines](https://developer.gnome.org/hig), it doesn't necessarily prevent adding options, but the guiding principle is to make things as simple as possible. In the case of options, we are trying to add as few as practical - and just set up the tool with good defaults.

Looking at other GNOME apps, I don't see that any have language settings (I looked at Builder, GEdit, Fractal, and Web). Users select the language they want for their desktop environment, and then the apps are all set to that language. After all, Gaphor should ideally be closely setup and integrated with your environment. If you want dark mode and Swedish, Gaphor should be able to do that too.

Is the main issue here, lack of translation for some languages like Swedish? I see that we are only at 24% for that language, which isn't great. Do you find yourself overriding languages with other apps in your environment?

Maybe instead of a language picker, we should have a minimum translation level prior to using it with the app, like <80% and you just get English.

**Comment by amolenaar** [comment]
I prefer following the GNOME HIG as well.

> Maybe instead of a language picker, we should have a minimum translation level prior to using it with the app, like <80% and you just get English.

Wouldn't that be an incentive _not_ to translate content. The solution is simple: fix the translation.

**Comment by danyeaw** [comment]
I meant if someone creates a new translation and translates only 10% of strings, we are probably providing a worse experience showing just a few things translated than if we just show English.

**Comment by amolenaar** [comment]
I had a quick check, but I'm not sure how to determine if the translation level is below a certain percentage.

**Comment by danyeaw** [comment]
Closed by #2442. We just released version 2.19.2 and Swedish isn't one of the mature translations and will remain in full English until it is.

@all-contributors please add @flatrick for idea
