### ISSUE TITLE
Coffee Machine example file "not valid"

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#2361]
### Describe the bug
When opening the example "coffee-machine.gaphor". Pop up says "Unable to open model.....does not contain a valid model"
### To Reproduce
1. Download examples/coffee-machine
2. Open file in gaphor

### Screenshots
<img width="480" alt="coffee-machine-invalid-file" src="https://github.com/gaphor/gaphor/assets/50702106/4e43a0b5-3570-420c-b2c3-1cf6f93dbb21">

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ x] macOS
- [ ] Windows

### Version
2.18.1

**Comment by amolenaar** [comment]
Hi @mikekidner, indeed, the model is compatible with the released version of Gaphor. This is because we implemented Item Flow on Associations, which will be part of Gaphor 2.19.

You can download https://github.com/gaphor/gaphor/blob/41b44c459b37ec323cbdf54883b01509714867a1/examples/coffee-machine.gaphor: it does not yet contain item flows on associations.

**Comment by mikekidner** [comment]
Thanks @amolenaar. Looking forward to 2.19.
