### ISSUE TITLE
Note or Remark box is different between diagrams for the same block

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#2522]
### Describe the bug
Notes missing from blocks across different diagrams. 

Writing a note in the note or remark box will show up on a given block in one diagram but the note or remark is not visible in other diagrams (the box is blank).

### To Reproduce
1. Create a diagram A
2. Add a block A
3. Create a new diagram B
4. drag the previous block A onto the diagram
5. Add a comment in the `note or remark` box for block A
6. check block A on diagram A
7. Notice text is missing

### Expected behavior
I expected notes attached to a block to travel with the block.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19.2

**Comment by sz332** [comment]
This is even true for a simple class diagram, creating a class.

**Comment by sz332** [comment]
@danyeaw @amolenaar it looks like that Note/Remark is associated to a diagram element and not a model element. Is it a bug or a feature?

**Comment by amolenaar** [comment]
The note should be on the model element. This is a bug for sure.

**Comment by sz332** [comment]
The problem is around propertypages.py. 

It seems that self.subject is pointing to gaphor.UML.classes.klass.ClassItem for class NotePropertyPage which is a visual representation of the model element and not the model element itself.

Is this a problem? (without knowing the internals I would say that any property setting in general should work on the model element itself and not the visual representation UNLESS we are really want to modify the visual representation)

It also seems that when we drag an existing model element into a new diagram then no new uuid is generated for the new ClassItem. That in my opinion is a bug, but might be unrelated.

@amolenaar any idea how to progress?

**Comment by amolenaar** [comment]
> (without knowing the internals I would say that any property setting in general should work on the model element itself and not the visual representation UNLESS we are really want to modify the visual representation)

I would expect that too.

> It also seems that when we drag an existing model element into a new diagram then no new uuid is generated for the new ClassItem. That in my opinion is a bug, but might be unrelated.

That would be a serious issue, since elements (also ClassItem) are managed by their id. I'm not able to reproduce it. Can you create an issue for this with steps to reproduce?

> @amolenaar any idea how to progress?

For the property editor we check the model element and then the presentation. I think the presentation is overriding the model element at some point. However, it would also need a migration (upgrade) so the remark is moved from the presentation to the model element.

**Comment by sz332** [comment]
It is very interesting because I tried to debug other parts (like changing the name) and it seems that in that case we are actually using model element and not presentation element.

Also when dragging from the model tree what I see is the type of the element being dragged is ClassItem instead of item, which I just don't understand. Is it by design?

**Comment by amolenaar** [comment]
> It is very interesting because I tried to debug other parts (like changing the name) and it seems that in that case we are actually using model element and not presentation element.

Yes, the property editor looks at both the model element and presentation item.

I added #2524 for the "ClassItem" issue.

**Comment by sz332** [comment]
Moving forward with this bug. Item in this case is an ClassItem.

It seems that two instance of PropertyPages is being created (__init__ is being called twice). First it is being called by a normal model element (gaphor.UML.uml.Class) then with a presentation representation (gaphor.UML.classes.klass.ClassItem).

elementeditor.py:

![image](https://github.com/gaphor/gaphor/assets/8182138/2f190cb9-cd7c-4570-b33c-1f4f4f953e8b)

propertypages.py:

![image](https://github.com/gaphor/gaphor/assets/8182138/cf381a47-8818-4ee3-9a76-0d72041cf6b8)

As I understand the exact same code tries to work with both a presentation element and a model element. Is it by design or is it a actually a bug? (since there are no type definitions being used I cannot decide what's the expected behavior at this point). Any idea?

**Comment by amolenaar** [comment]
I created #2525, which will fix this issue: notes are always attached to the model element.

I think, also by looking at the original tests, that I had not thought this through.

**Comment by danyeaw** [comment]
@all-contributors please add @tompkins-ct for bug

**Comment by danyeaw** [comment]
Thanks @tompkins-ct for the bug report! :1st_place_medal:
