### ISSUE TITLE
Removal of block def. diagram removes also a relationship

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2616]
### Describe the bug

Removal of block def. diagram removes also a relationship between block elements when Remove unused elements is switched off.

### To Reproduce
1. Create a new BDD
2. Add two blocks
3. Create a composite association between them
4. The relationship is visible in the model
5. Delete the diagram
6. The relationship is removed 

### Expected behavior

Removal of a diagram shall not remove relationships (nor elements) when this mode is switched off.

### Screenshots

Before:

![image](https://github.com/gaphor/gaphor/assets/8182138/7ad882a2-b850-4703-9969-b36055506f09)

After:

![image](https://github.com/gaphor/gaphor/assets/8182138/f2396ce6-0502-46b9-a9c1-08cc288b5750)

### OS
- [X] Linux (Ubuntu Latest)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19.3

**Comment by danyeaw** [comment]
Thanks @sz332! I can reproduce this, and it looks like it a more general issue, it happens with any diagram type and any relationship.

**Comment by sz332** [comment]
Taking a swing at this.

**Comment by sz332** [comment]
The way I understand we are unlinking the diagram element from the model element. But this as an event also indicates the deletion of the element, which is not good. I think this is more like an architectural issue.

@danyeaw

**Comment by amolenaar** [comment]
My hypothesis is:

When a diagram is removed all presentations on that diagram are automatically removed. This is expected, since presentations are owned by a diagram. The presentation does not own the underlying model element (subject), though. 

Since elements are removed from the diagram, their disconnect handlers are triggered. I think this is what triggers the removal of the relations.
