### ISSUE TITLE
Signature lines avoid overlay on the node.

### ISSUE THREAD

**Issue by gavr123456789** [gaphor/gaphor#308]
### I'm submitting a...
- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

### Current behavior
The header label of the Connector element does not evade the node.

### Expected behavior
The header label of the Connector element turns away from the node.
### System Information
OS:
- [x] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:
The label only dodges when it intersects with the Connector.

SCREENSHOT:
![изображение](https://user-images.githubusercontent.com/30507409/81068695-733b1f00-8ee9-11ea-8145-a37ab569f252.png)
![изображение](https://user-images.githubusercontent.com/30507409/81068773-95cd3800-8ee9-11ea-9bba-0ae58dba12da.png)

**Comment by amolenaar** [comment]
Thanks for your feedback.

Currently associations use some heuristics to figure out how to display the name and multiplicity at the end of the association line.

If the line is (pretty much) horizontal or vertical, name and multiplicity are displayed on both sides of the line. Otherwise both are displayed on the same side, depending on the angle of the line.
In doing so, the association is not aware of the side it's connected on a class or interface.

It may be worthwhile to investigate if that's possible.

Just out of curiosity: why don't you attach the lines to the top/bottom of the classes? That way the text on the association end will not overlap the class.

**Comment by danyeaw** [comment]
@allcontributors please add @gavr123456789 for ideas
