### ISSUE TITLE
Consider using raised toolbar styling

### ISSUE THREAD

**Issue by bragefuglseth** [gaphor/gaphor#3177]
### Is your feature request related to a problem?

The editor looks awkward tue to the right sidebar seemingly disappearing into nothing

### Describe the solution you'd like

Libadwaita's toolbar view (which the app should be ported to at this point) has a built-in property to raise the toolbar (header bar) in cases like this. It should probably be used. In addition, overlay split could be used for the sidebars.

## Current state

![Skjermbilde fra 2024-03-11 07-28-41](https://github.com/gaphor/gaphor/assets/91388039/4bd77284-c8bc-40ac-afaf-25ac28e5aa94)

**Comment by amolenaar** [comment]
I looked into the toolbar view, but haven't got around porting to it. Due to the internal structure of Gaphor it's a bit more difficult than just changing the `.ui` files unfortunately. (something that should be addressed too)

@bertob Do you have an opinion on the header bar style?

**Comment by bertob** [comment]
Long-term we probably want to use a split view with ToolbarView here (similar to e.g. Sysprof and Builder). I'm not sure what exactly that would entail, but I'd start by moving the primary menu to the left and the plus button to the center pane and making the window three vertically separate panels.

It could also be a nice opportunity to merge some of the sub-toolbar buttons on the right side into the headerbar itself, so maybe it could have some other structural advantages as well :thinking:

**Comment by amolenaar** [comment]
The right side should be relatively easy to convert to a SplitView. The left side is now made with GtkPaned, which allows the user to resize. This is (currently) not possible with split views AFAIK.

I added a border above the "Open a Diagram" status page. I like to stick to the flat layout, since it looks more integrated with other OS'es (in particular macOS, which I use a lot).

**Comment by amolenaar** [comment]
Is this what you had in mind?

The right sidebar looks nice. If I remove the minimize/maximize buttons, the toolbar can move to the header bar.

The left side looks a bit weird to me. The top-left header bit looks a bit out pf place.

<img width="972" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/5bc123aa-81dc-4739-a1a6-50535ab7e217">

**Comment by bertob** [comment]
More or less, yeah. Where exactly to move the undo/redo/zoom buttons is a bit tricky maybe, since these are probably useful when the sidebar is hidden. Maybe undo/redo and preferences could be in the middle sidebar, and the zoom buttons could be overlaid OSD buttons in the bottom right of the canvas, like in e.g. Maps?

As for the left side, I think it'd be ok as a next step if it used the same color for the entire panel rather than the object tree background being white. Longer-term it might be good to find a better spot for the UML/SysML/etc switcher, but I don't know the use cases for it well enough. Is this something people change often? If not, could it be a submenu in the primary menu?

**Comment by amolenaar** [comment]
> More or less, yeah. Where exactly to move the undo/redo/zoom buttons is a bit tricky maybe, since these are probably useful when the sidebar is hidden. 

We can also leave them out, since there's keyboard shortcuts for them as well.

> Maybe undo/redo and preferences could be in the middle sidebar, and the zoom buttons could be overlaid OSD buttons in the bottom right of the canvas, like in e.g. Maps?

Undo/redo in the middle header bar I suppose? I have to catch up on what's new for GNOME 46.

> As for the left side, I think it'd be ok as a next step if it used the same color for the entire panel rather than the object tree background being white. 

> Longer-term it might be good to find a better spot for the UML/SysML/etc switcher, but I don't know the use cases for it well enough. Is this something people change often? If not, could it be a submenu in the primary menu?

The switcher is (probably) not changed that often, but it changes the proposed diagram types in the tree view context menu and changes the bottom-left toolbar. It may be good to know which profile is active.

And what about the colors? The left and right sidebar should have the same color, right?

<img width="1180" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/ad80c03c-592b-4324-95cb-ba010162015a">

**Comment by bertob** [comment]
I guess this works as a next step, except for the headerbar/tab bar background mismatch in the center pane.

As for the sidebar colors, yes, they should both use the default sidebar colors, but not sure what the standard way to achieve that is. Might be good to ask in #libadwaita :)

**Comment by amolenaar** [comment]
How 'bout this?

<img width="1136" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/b95afe35-3dff-404b-ba20-b5d280d2752e">

The left pane is still based on GtkPaned, so it can be resized, but with the same style as the (right side) property editor.

**Comment by bertob** [comment]
Looks good to me :+1:

**Comment by danyeaw** [comment]
@all-contributors please add @bragefuglseth for design
