### ISSUE TITLE
Exception when creating wrong diagram type in SysML

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#3194]
### To Reproduce
1. Select SysML profile
2. Create a Block
3. Select Activity Diagram from the `+` menu

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

```
|Traceback (most recent call last):
|  File "/Users/arjan/Development/gaphor/gaphor/ui/actiongroup.py", line 141, in _action_activate
|    method(from_variant(param))
|    │      │            └ GLib.Variant('s', 'act')
|    │      └ <function from_variant at 0x102491760>
|    └ <bound method ModelBrowser.tree_view_create_diagram of <gaphor.ui.modelbrowser.ModelBrowser object at 0x10ecbbe90>>
|  File "/Users/arjan/Development/gaphor/gaphor/ui/modelbrowser.py", line 195, in tree_view_create_diagram
|    diagram = diagram_type.create(self.element_factory, element)
|              │                   │                     └ <gaphor.SysML.sysml.ValueType element 84dc1b12-d808-11ee-bd8f-be7f4daace3f>
|              │                   └ <gaphor.ui.modelbrowser.ModelBrowser object at 0x10ecbbe90>
|              └ <gaphor.SysML.diagramtype.SysMLDiagramType object at 0x10dfe20d0>
|  File "/Users/arjan/Development/gaphor/gaphor/SysML/diagramtype.py", line 32, in create
|    d = next(d for d in self._defaults if isinstance(element, d.from_type))
|                        │                            └ <gaphor.SysML.sysml.ValueType element 84dc1b12-d808-11ee-bd8f-be7f4daace3f>
|                        └ <gaphor.SysML.diagramtype.SysMLDiagramType object at 0x10dfe20d0>
|StopIteration
```

### Expected behavior

Either a notification or the menu item should be insensitive or hidden.

### Version
Version of Gaphor: 2.24

**Comment by danyeaw** [comment]
An Activity Diagram is a valid diagram type when working with SysML. The issue is that an Activity Diagram can't be nested under a Block. It is also kind of weird that it can be nested under a Class currently, I'm not sure if UML allows that or not.

Maybe we should make the menu sensitive to which diagrams you are currently allowed to create based on what you have selected?

**Comment by amolenaar** [comment]
That would be a second step IMHO. I'm happy with @FranciscoTGouveia's fix for now.

**Comment by danyeaw** [comment]
I agree that it is a great first step. Maybe in the warning we should say Can't create New Activity Diagram nested under a Block, rather than say it is due to having the SysML profile selected? That way the user will select a different element to nest the diagram under rather than changing profiles, which isn't the right step to take.
