### ISSUE TITLE
Discussion: Removing changelog from document translation

### ISSUE THREAD

**Issue by yakushabb** [gaphor/gaphor#3234]
The translatable documentation contains 1,754 strings.

It appears that 558 strings (31% of all translatable document strings) come from the CHANGELOG.md file.

While the changelog might be useful for developers, it's not the best way to present important information that could be useful for end users.

I suggest removing these strings from document translation and creating a new file highlights changes that are not backwards compatible.

**Comment by amolenaar** [comment]
Is that because the changelog is included from [docs/changelog.rst](https://github.com/gaphor/gaphor/blob/main/docs/changelog.rst)?

**Comment by danyeaw** [comment]
@amolenaar Yes, I think so. Sphinx doesn't actually support excluding files or portions of files from translation, there is an enhancement request here:
https://github.com/sphinx-doc/sphinx/issues/11787

Instead of putting the changelog inline, we could link to the changelog.md file in GitHub as a workaround.

**Comment by amolenaar** [comment]
That sounds like a good solution.
