### ISSUE TITLE
Error when installing Gaphor (Windows client) 

### ISSUE THREAD

**Issue by Icon210** [gaphor/gaphor#3265]
Windows OS (10 & 11) reports an error 'malware' in the installation... 04-20/24 (for both Installer & Portable versions)

**Comment by danyeaw** [comment]
Hi @Icon210, sorry you ran in to this, and thanks for reporting the issue. Unfortunately, there isn't much we can do since there isn't malware in Gaphor. We are continuing to try to improve PyInstaller which we use to package Gaphor to help prevent this, and I have a couple more ideas. Let's continue the discussion over at https://github.com/gaphor/gaphor/discussions/3157. We also greatly appreciate you reporting false positives to the virus companies as well.
