### ISSUE TITLE
Add Mermaid Diagram Syntax Support and Markdown Export Capability

### ISSUE THREAD

**Issue by dmferrari** [gaphor/gaphor#3289]
### Is your feature request related to a problem?
No. It's a feature request: Gaphor currently does not support Mermaid syntax, which limits the ability to work with text-based, markdown-like diagramming directly within the tool.

### Describe the solution you'd like
I suggest that Gaphor includes support for creating and editing diagrams using Mermaid syntax and adds functionality to export diagrams into Mermaid markdown. This integration would facilitate diagram management alongside code, especially in environments where version control and documentation are critical.

### Describe alternatives you've considered
I currently use VSCode with markdown extensions to handle Mermaid diagrams. Ex.: [Markdown Preview Mermaid Support](https://github.com/mjbvz/vscode-markdown-mermaid)

While effective, this method requires managing diagrams outside of Gaphor, which complicates workflows that benefit from integrating visual and text-based diagramming.

### Additional context
Adding Mermaid support would enhance Gaphor's appeal to a broader audience, particularly those in software development and technical documentation, by bridging the gap between visual and code-based diagramming.

**Comment by amolenaar** [comment]
Hi @dmferrari, thank you for your feature request.

Gaphor is more than just a simple diagram editor. Diagrams are just a view on the [model](https://insights.sei.cmu.edu/blog/introduction-model-based-systems-engineering-mbse/) that you create. This is different from creating (only) images with tools like Mermaid, and DrawIO.

But yes, we want means to define models and diagrams in a textual manner.

This issue seems related to #615.

**Comment by dmferrari** [comment]
Thanks @amolenaar 

Closing this then! :)
