### ISSUE TITLE
Dangling connector ends

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#3445]
### Describe the bug
Loading a large model developed with previous Gaphor versions (11815 elements). Several connector elements in the model are dangling. Dragging the dangling item to a diagram gives an error. These items can't be deleted (delete key or right-click).

### To Reproduce
1. Run `poetry run gaphor` / Open Gaphor
2. Open model
3. See lots of blank items

### Expected behavior
Dangling items should not be present.

### Screenshots

![image](https://github.com/user-attachments/assets/7adc83d1-8723-4423-a35c-0717f90e2cb0)
![image](https://github.com/user-attachments/assets/9f39c1d6-94bf-413e-bc6d-e31a15ef38bb)

Error when dragging to screen:
```
(gaphor:12688): Gdk-CRITICAL **: 11:04:59.086: _gdk_macos_surface_update_fullscreen_state: assertion 'GDK_IS_MACOS_SURFACE (self)' failed
```

Note: the following bug shows on the terminal during startup with poetry:
`UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable`

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS (M2 Pro, Sonoma 14.5)
- [ ] Windows

### Version
Version of Gaphor: 2.26 (and develop)

**Comment by amolenaar** [comment]
Thanks @tompkins-ct,

It it correct that you should [not be able to delete those elements](https://github.com/gaphor/gaphor/blob/main/gaphor/UML/deletable.py#L5-L7). They should, however, be children of a `Connector`. Not sure why that's not the case.

**Comment by amolenaar** [comment]
`examples/coffee-machine.gaphor` has the same issue.

**Comment by teunhoevenaars** [comment]
Hi @amolenaar, I dId a quick test to pinpoint the commit that first introduced these dangling connector ends. Hopefully this is of help.

Method used to identify commit
1. checked out an older commit
2. ran `poetry install`
3. ran `poetry run pre-commit install`
4. ran `poetry run gaphor`
5. open the SysML Example
6. check whether there were dangling references

Results:
- commit https://github.com/gaphor/gaphor/commit/4fb7a9e8fc3ca69a07e08fa868633e45fb04a8a4 does not have the dangling references
- the next Merge pull request commit, https://github.com/gaphor/gaphor/commit/7ce454752eca69d4b8c3b6c0eb1ca8326fbaaa20, does have the dangling references.
- zooming into the commits making up that MR, the issue seems to originates in commit https://github.com/gaphor/gaphor/commit/179d1cc463f38cb06a49c715771870975030f495
