### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by jischebeck** [gaphor/gaphor#49]
It would be great to have a python 3 compatible version of gaphor.

**Comment by danyeaw** [comment]
@jischebeck Thanks for submitting the issue. This is what I am working on right now. To get gaphor to Python 3, we need to upgrade gaphor and all of its libraries from PyGTK (Gtk2) to PyGObject (Gtk3), and do the conversion to Python 3.
Gaphas is almost there with https://github.com/gaphor/gaphas/pull/20
etk.docking has changes merged with https://github.com/dieterv/etk.docking/pull/5
Gaphor is a work in progress, I am first trying to get all tests to pass with https://github.com/gaphor/gaphor/pull/48 and then I will start to do the conversion.
There are also some concerns with the Drag and Drop implementation in etk.docking, so that may require some surgery to remove etk.docking.

If you are interested, I would be happy to have any help :heart:

**Comment by danyeaw** [comment]
#50 and #51 are now merged. We have Python 3 compatible forward ported syntax. The next steps will be to port to PyGObject and deal with etk.docking.

**Comment by amolenaar** [comment]
This issue can be closed, right?

**Comment by danyeaw** [comment]
@amolenaar I think so, I guess I was waiting until we get a new version packaged with at least a release candidate.

**Comment by danyeaw** [comment]
@jischebeck Python 3 is now fully supported with all tests passing.

To install Gaphor in Linux use Flatpak:

1. [Install Flatpak](https://flatpak.org/setup)
1. `flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`
1. `flatpak install --user org.gaphor.Gaphor`

We are currently working on installation packages for Windows (almost done!) and macOS. Until
that is ready, you can install Gaphor, using pip:

```bash
$ pip install --pre gaphor
$ source ./venv
$ gaphor
