### ISSUE TITLE
Left-align sidebar headers

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#498]
**Describe the bug**
The sidebar headers are centered, while the content of each category is left-aligned. This results in a pretty weird layout:

![image](https://user-images.githubusercontent.com/1908896/97040574-6c26cc80-156e-11eb-9206-52652f2b89a8.png)

I think left-aligning the headers would make the layout feel a lot less disjointed and easier to scan.

**OS**
- [x] Linux (Fedora 33)

**Version**
Version of Gaphor: 2.0.1 from Flathub

**Comment by danielvictory** [comment]
Hello!  I created a GitHub account just to log in and say that I am very interested in trying to lend a hand with this!  As a general introduction, because my account is empty at the moment, I have completed a python programming course on a education site called DataCamp, but have not yet built anything meaningful or contributed anywhere.  From everything that I have read though, the best way to learn is to just jump in and going to open source as quickly as possible is an excellent methodology.

What I think I am seeing so far:
This alignment is most likely controlled between the layout .css, .py, and/or .xml files.
Because this change is just something in the graphical interface, it shouldn't be affecting any classes/functions/settings and therefore may not need any additional tests or test updating (although I am also interested in your "move to pytest" open issue).
The .css is controlling the framing and appearance, the .py is setting up the call functions to build out the tree with the component names, and the .xml is setting the way those frames and names are displayed.
Is this potentially as simple as changing the alignment in the xml?

Next steps here are to create the fork, download and work to shift the alignment and then reupload and initiate a pull request, correct?  Let me know if I am on the right track and I will start to move!

Also, please let me know if I am violating any unwritten rules or anything by asking so many questions, haha.  I am quite new here.

**Comment by danyeaw** [comment]
@danielvictory It sounds like you are on the right track and I am looking forward to your contribution! :+1:

**Comment by amolenaar** [comment]
@danielvictory I really appreciate you want to help out. Thanks!

Let me give you some guidance. Although a lot of UI is defined in xml (Glade) files, this particular bit isn't ;). The toolbox is created in this method: [`gaphor.uit.toolbox.Toolbox.create_toolbox()`](https://github.com/gaphor/gaphor/blob/master/gaphor/ui/toolbox.py#L97). The documentation on `Gtk.ToolItemGroup` can be found on https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/ToolItemGroup.html.

I'm not sure if you can manage with just a bit of CSS or whether you have to use a custom `label_widget` for the item group.

**Comment by danielvictory** [comment]
Thank you @amolenaar!  That was super helpful and I will check it out.

**Comment by danielvictory** [comment]
Hey everyone, life has kept me from making any meaningful attempt in the past two weeks, but I am still interested in fixing this issue if it is still open.  Just checking in to let y'all know that it is on my mind still!

**Comment by danyeaw** [comment]
@danielvictory How are things going, any help needed?

**Comment by danielvictory** [comment]
Status still the same.  Without going into too much detail, my normal work and life have conspired to keep me away from Github.  I hope to close the issue by the end of the year though if that's not too long of a time frame.  If this issue needs to be solved sooner, please let me know and I can relinquish.  I appreciate the check in though!

**Comment by danielvictory** [comment]
Good morning!  Thanks for checking in with me on the issue I assigned myself.  It prompted me to get myself in gear and make time for this.  So far it has been a pretty steep learning curve, but all interesting.  

I'm having trouble with the virtual environment creation through mysys so will have to troubleshoot that further, but seems like I may have a good gtk solution from [this SO post.](https://stackoverflow.com/questions/24994255/how-to-left-align-a-gtk-label-when-its-width-is-set-by-gtksizegroup) And here's the [gtk documentation.](https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-xalign)

A general question: what's the best way to update or ask questions going forward?  A quick post here? Or in the gitter room (which I have joined now!)?  Or should I start some sort of text file?

Thanks!

**Comment by danyeaw** [comment]
@danielvictory Here or on Gitter are both fine options. 👍

**Comment by danielvictory** [comment]
For now I will drop my difficulties here so that I don't take up space for the discussion on Gitter.

I am having significant trouble even getting a development gaphor on my computer.  Recently got a new mac for the first time so there has been a learning curve there too, which doesn't help.

Somehow the program is not finding gtk+3 correctly and I can not figure out why.  I have the shell profile pointing toward the homebrew python3 and pip3, but it can not find the gtk+3.  Any thoughts?

Terminal output below.  Tried to clean up some of the text for legibility.

`mymac@MyMacs-MacBook-Pro ~ % cd gaphor
mymac@MyMacs-MacBook-Pro gaphor % source ./venv
Are we on Macos with Homebrew installed? Yes
Adding libffi pkg-config path /usr/local/Cellar/libffi/3.3/lib/pkgconfig to $PKG_CONFIG_PATH
Are we on MSys (Windows)? No
Checking: python3 --version
Checking: pkg-config --print-errors --exists gobject-introspection-1.0 >= 1.46.0
Gtk3 is not installed in a way it can be loaded in Python.

The Command used to test this:

    >>> from gi.repository import Gtk

Please read the installation instructions on https://gaphor.readthedocs.io.
mymac@MyMacs-MacBook-Pro gaphor % which Gtk
Gtk not found
mymac@MyMacs-MacBook-Pro gaphor % brew install gtk+3
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

Warning: gtk+3 3.24.24 is already installed and up-to-date
To reinstall 3.24.24, run `brew reinstall gtk+3`
mymac@MyMacs-MacBook-Pro gaphor % which gtk+3
gtk+3 not found
mymac@MyMacs-MacBook-Pro gaphor % cd ..
mymac@MyMacs-MacBook-Pro ~ % cd /

mymac@MyMacs-MacBook-Pro / % cd usr

mymac@MyMacs-MacBook-Pro /usr % cd local

mymac@MyMacs-MacBook-Pro local % cd Cellar
mymac@MyMacs-MacBook-Pro Cellar % ls
adwaita-icon-theme	gsettings-desktop-schemas	libtiff
atk				         gtk+				         lzo
cairo				gtk+3				         openssl@1.1
fontconfig			gtk-mac-integration		pango
freetype			        harfbuzz			                 pcre
fribidi				hicolor-icon-theme		        pixman
gdbm				icu4c				        pkg-config
gdk-pixbuf			jpeg				                python@3.9
gettext				libepoxy			                readline
glib				        libffi				                sqlite
gobject-introspection	libpng				        xz
graphite2			librsvg`

**Comment by danyeaw** [comment]
@danielvictory Did you try to install all the dependencies that are on our [Gaphor in macOS](https://gaphor.readthedocs.io/en/latest/macos.html) page?

```brew install python3 gobject-introspection gtk+3 adwaita-icon-theme gtk-mac-integration```

The errors sound like you may be missing gobject-introspection to me.

**Comment by danielvictory** [comment]
I copy and pasted straight from the bar, yep.  I will go back and check it out.  Somehow it is not pointing to the correct place.

**Comment by danyeaw** [comment]
@danielvictory Were you able to resolve this issue?

**Comment by AcousticCh** [comment]
I see this is still open, i am a beginner to python that would be happy to pull a copy and try my hand at it if your issue has not been resolved

**Comment by danielvictory** [comment]
Apologies to all for disappearing before, got overwhelmed. But thanks for giving me the shot!
So yes @AcousticCh, it is still open.  I assume that the gaphor team will let you have a crack at it too! I found some resources that may be helpful, linked in my Dec 1 comment.

**Comment by danyeaw** [comment]
Hi @AcousticCh, welcome to the project! Yes, we would be glad to have your help fixing this. If you need any guidance please ask away on here or on [Gitter](https://gitter.im/gaphor/Lobby).

**Comment by AcousticCh** [comment]
Thank you all very much I'm excited for this next step toward my
programming advancement most excited about being able to converse with
other programmers for the first time ever really I will make time to look
at things in better detail tomorrow and I apologize if I dont respond for a
few hours at any point I'm probably under a car and yes that includes
anytime from breakfast back around to 3 am :)

**Comment by AcousticCh** [comment]
afternoon everybody, ill make a Gitter account in a little bit. last night I put an hour or so figuring out how to complete my task. started by finding the styling files and all the toolbox files, then I downloaded Gaphor and read some on the GTK.ToolItemGroup documentation and replicated the flowchart on that page with Gaphor(Beautiful tool by by the way I've been looking for an offline powerful app like this), today i intended to make a better understanding of gtk methods, and mark on my chart where each method would be in that system, read some about glade(kind of looks like someone took away minimal functionality from css and put it together with html as neat markup language, am i right?) then use practice some gtk in my own little code and strike at realigning those headers tomorrow after sufficient planning. i will drop my before and after gaphor chart here, please provide criticism on my plan of attack and let me know how you would go about it at my programming level if my plan is not a good way to go through the first repository of this size that ive touched yet!! thank you

**Comment by amolenaar** [comment]
Hi @AcousticCh,

Yes, glade files provide the markup for the UI. They can be viewed and edited with Glade, the tool. (there's also a layout.xml in the gaphor.ui package, but that's not a glade file ;) ).

The toolbox (ToolPalette and friends) stuff is all coded in Python, though.

If you want, you can also replace `ToolPalette` with `Expander` and use `FlowBox` for the buttons. We need this once we want to support GTK 4 (#618).

**Comment by AcousticCh** [comment]
@amolenaar look like i got some new tools to learn thank you ill update my progress tomorrow

**Comment by AcousticCh** [comment]
had to build a plow before I got to this but now I'm confused I cant seem to make gtk or glade tools download on my windows 10, or 7, constant error from cmd prompt saying packages and dependencies don't exist, I know I can manage on my parrot linux. but as glade documentation mentions its for GNOME, do I have to change my kde plasma environment to GNOME before I can install and make use of the tools or should I be able to set this environment up with kde. thought I would ask here for a clear answer but I will be hunting online for it in hopes of finding my own answers first.

**Comment by AcousticCh** [comment]
Found my solution after a few uninstall/reinstalls and going a few chapters deep into the linux certification course from linux foundation, installing my environment now :)

**Comment by AcousticCh** [comment]
and yes i would be excitedly ready to continue my learning of this environment and replaceing the tool palette with expander after my initial assignment

**Comment by amolenaar** [comment]
@AcousticCh You can run GTK based applications in Plasma just fine. Both projects participate on freedesktop.org to ensure both platforms work nicely with one anothers applications.

Regarding the windows tooling (MSys): it may be that you hit a mirror that was in the process of updating. Is it still a problem to install?

**Comment by AcousticCh** [comment]
@amolenaar i did get my environment downloaded/installed (common beginners linux mistake that i resolved last month and did not consider when i wanted to refresh and reinstall my os) and i have been messing around making my own little gui which is improving my understanding of gaphors filesystem and code as well as enforcing the memory of what i read. im stepping closer to being comfortable with my first contribution, i hope the few days im taking as a beginner is not an issue in itself i did try to pickup an issue that seemed forgotten or ignored so i could pace myself but not take 2 weeks

**Comment by danyeaw** [comment]
Closed by #702
