### ISSUE TITLE
Flathub packaging issue

### ISSUE THREAD

**Issue by artscoop** [gaphor/gaphor#838]
**Describe the bug**
The package Gaphor cannot be found on Flathub by looking for the strings "UML", "Design", "Draw", "SysML", "RAAML". That's how I found Gaphor randomly and not on purpose. I really think this is an issue.
The software only appears with the word "Modeling", between entries of 3D software and other apps completely unrelated.

**To Reproduce**
1. Go to flathub
2. Search "UML"
3. See that Gaphor does not appear, yet UML is why the software exists in the first place.

**Expected behavior**
Gaphor appears in the list.

**OS**
- [x] Linux (Flatpak)

NOTES:

**Version**
N/A

**Additional context**
The description of the package on Flathub is a very short sentence with a very broad meaning, which makes the package basically invisible.

**Comment by danyeaw** [comment]
@all-contributors please add @artscoop for bug

**Comment by danyeaw** [comment]
@artscoop Thanks for the big report, we really appreciate it!

The flatpak gets built for flathub from the repository here: https://github.com/flathub/org.gaphor.Gaphor
The metadata info is located in this file: https://github.com/flathub/org.gaphor.Gaphor/blob/master/share/org.gaphor.Gaphor.appdata.xml

I don't think that the [Metadata spec](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html) actually has a section for keywords. There is also a [Metainfo creator](https://www.freedesktop.org/software/appstream/metainfocreator/#/guiapp) that shows another simplified view of the types of information that you can have in the appdata.xml.

Since there is no special keywords tag, maybe we should make the description longer to include some of these keywords. Is this something you would be interested in helping us with by submitting a pull request to update the metadata info?

**Comment by artscoop** [comment]
Hey Dan,
Thanks for your answer!

As it's a low hanging fruit, of course I can and I will change the description for the package metadata
I'll open a pull request most probably in less than one hour so it can be reviewed

Thanks again!

**Comment by mathiascode** [comment]
You could also add a `Keywords` section to the .desktop file. These seem to be picked up by the search feature on Flathub.

**Comment by danyeaw** [comment]
@mathiascode Thanks, that is a great suggestion as well!

**Comment by danyeaw** [comment]
@all-contributors please add @artscoop for code

**Comment by danyeaw** [comment]
Thanks @artscoop for the contribution!
