### ISSUE TITLE
Easier zoom in/out and horizontaly shift

### ISSUE THREAD

**Issue by tomaszdrozdz** [gaphor/gaphor#877]
How about:
- allowing to easier zoom in/out with "ctrl" and mouse scroll ?
- allowing to easier "shift" horizontally with "shift" and mouse scroll ?

**Comment by amolenaar** [comment]
Hi @tomaszdrozdz,

Thanks for reaching out :smiley:.

Let me look into this. I use a track-pad all the time, so I think this behavior has not been tested properly on our side.

**Comment by danyeaw** [comment]
@allcontributors-bot please add @tomaszdrozdz for idea

**Comment by danyeaw** [comment]
@allcontributors please add @tomaszdrozdz for idea

**Comment by mrmonkington** [comment]
+1 as it is a little tricky navigating a larger diagram using a desktop + conventional mouse.

Prior art from other popular drawing/graphing tools (Inkscape, Xdot, Dia, Draw.io, Lucidchart):

 - middle-click+drag to pan around
 - less commonly space+drag to pan
 - CTRL+"=" to zoom in (so that you do not need to use shift to achieve "+")
 - CTRL+wheel to zoom

**Comment by danyeaw** [comment]
Closed by #913.
