### ISSUE TITLE
Diagram type support

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#973]
Currently there is a common type of diagram. Instead of having a common diagram, as I user, I would like to be able to create a diagram type (like block definition diagram, sequence diagram, activity diagram, etc.) and the ability to use only those elements in the diagrams which are applicable.

**Comment by danyeaw** [comment]
@all-contributors please add @sz332 for idea

**Comment by danyeaw** [comment]
I think it is one of the aspects that many people familiar with modeling expect from a modeling tool as opposed to a drawing tool. I think there are some strong advantages and disadvantages that we should consider.

Some advantages:

1. The tool can simplify or collapse parts of the toolbox based on the type of diagram open, and add the gray out guidance.
1. We could add the diagram frame with the info in the upper left which provides additional context for someone else viewing your diagram.
1. We could add templates per diagram type to aid new users, for example if they select an activity diagram with templates enabled then it would start with a few swim lanes, activities, and object flows.

Some disadvantage:

1. Some additional complexity in the tool, because now we need dialogs to select all the different UML and SysML diagram types.
1. Also for a brand new modeler, I think we are making it a bit harder to get started because you have to know what elements go on which diagram type before you draw anything.
1. Less flexibility, no way to show views of the model that mix different elements from different diagram types like you could in a drawing tool.

**Comment by sz332** [comment]
Hello, what if we easen up the requirement. What if I say that **beside** having a general, all purpose diagram, I would like to have diagram types as well, which might or might not be constrained.

**Comment by vanillajonathan** [comment]
>  1. The tool can simplify or collapse parts of the toolbox based on the type of diagram open, and add the gray out guidance.
>  2. We could add the diagram frame with the info in the upper left which provides additional context for someone else viewing your diagram.

I like these ideas.

**Comment by amolenaar** [comment]
We can modify the behavior of the "New diagram" button in the header bar to show a popover with diagram types (_Class diagram_, _Sequence diagram_, etc.)

> We could add templates per diagram type to aid new users, for example if they select an activity diagram with templates enabled then it would start with a few swim lanes, activities, and object flows.

I think this is a tricky one, since that would imply that we "pollute" the model with template elements every time a user creates a new diagram.

What would the UX be like? Should the toolbox change for every diagram type? Should it only collapse the sections not applicable for a diagram type (but the elements can still be applied if the user sees fit)?

**Comment by vanillajonathan** [comment]
> We can modify the behavior of the "New diagram" button in the header bar to show a popover with diagram types (_Class diagram_, _Sequence diagram_, etc.)

Sounds reasonable to me.

> I think this is a tricky one, since that would imply that we "pollute" the model with template elements every time a user creates a new diagram.

I agree with you.

> What would the UX be like? Should the toolbox change for every diagram type? Should it only collapse the sections not applicable for a diagram type (but the elements can still be applied if the user sees fit)?

Either one would be fine with me.
It could change for the diagram but you could also introduce a "freestyle" (unconstrained, non-standard) diagram type.

**Comment by sz332** [comment]
Agree with @vanillajonathan

**Comment by amolenaar** [comment]
Workin' on it:

![image](https://user-images.githubusercontent.com/96249/146647897-bd95b378-aff9-4405-aa20-d9759b441dcf.png)

**Comment by sz332** [comment]
@amolenaar woooow, this looks awesome!!!

**Comment by amolenaar** [comment]
It's a starting point ;)

**Comment by vanillajonathan** [comment]
The user can pick profile from two places, from both the welcome screen and from the dropdown within the application window. I am not sure if it is desirable to have the profile selection in more than one place.

The "Open a Gaphor" model screen has a "Create New Model..." button that appears to not be functional.

I think the the create a new model and open existing model button are not needed and provide little of value. The models that the user wants to use are common, well-defined, declared and standardized, these are the UML, SysML, RAAML and C4 Model.

From within the application window the user can change the profile even after having done started working with it and done changes. I think this is undesirable because when a user has picked a profile and started using it (done changes) then he has committed to using that profile, if he wants to change profile he ought to have to start over with a new blank document. A document should not mix symbols/language from different profiles. I think the application should actively prevent misuse such as using symbols from different profiles in the same document.

When the user navigates between different diagram types the application expands and collapses the tool groups according to which diagram type is selected. This still allows the user to use any tool from any diagram type in any diagram type. I think instead of expanding/collapsing the tool groups should have their visibility toggled.

**Comment by danyeaw** [comment]
Hi @vanillajonathan, thanks for the additional feedback!

> The "Open a Gaphor" model screen has a "Create New Model..." button that appears to not be functional.

I opened #1300 to discuss this more.

> I think the the create a new model and open existing model button are not needed and provide little of value. The models that the user wants to use are common, well-defined, declared and standardized, these are the UML, SysML, RAAML and C4 Model.

I don't understand what you mean more, but maybe we can discuss it on #1300 as well?

> From within the application window the user can change the profile even after having done started working with it and done changes. I think this is undesirable because when a user has picked a profile and started using it (done changes) then he has committed to using that profile, if he wants to change profile he ought to have to start over with a new blank document. A document should not mix symbols/language from different profiles. I think the application should actively prevent misuse such as using symbols from different profiles in the same document.

An example where this is needed is that RAAML is a profile that is built on top of SysML. Users should be able to model a system and then in that same model be able to also do safety or reliability analysis. As a user, I wouldn't want to show all the SysML toolbars when I am doing my RAAML modeling, especially because we have about 6 more RAAML toolbars to add.

Most other modeling tools let you mix UML and SysML in the same model if you want to.

> When the user navigates between different diagram types the application expands and collapses the tool groups according to which diagram type is selected. This still allows the user to use any tool from any diagram type in any diagram type. I think instead of expanding/collapsing the tool groups should have their visibility toggled.

I think if we are going to do this, it should be an option to show an expert mode to show the others. This is how other modeling tools handle this. Should we make this a separate feature request to discuss more?
