### ISSUE TITLE
Activity parameter node support

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#974]
Activity parameter node is used to define input, output, input/output, or return value for an activity diagram. As a user, i would like to have the ability to add activity parameter nodes to a diagram.

**Comment by amolenaar** [comment]
Thanks. This feayire will make activity diagrams more complete.

In addition to this we should fix the nesting of activities.

(see section 15.4 Object Nodes)

**Comment by amolenaar** [comment]
First we need a presentation for `Activity`.

I was thinking: can we add Activity Parameter Nodes in a similar way as we add attributes and operations to a class, with an editable list in the property editor (right pane).
Reasoning: those nodes  can only be applied to activities, which makes it confusing if you want to drag one from the toolbox onto a diagram (I just experienced that when trying it with Visual Paradigm).

We already have a parser for parameters (e.g. `in text: String`). By having them tied to the activity it's also easier to move them around.

**Comment by sz332** [comment]
Yes, this might be a good enough solution. The way I normally model activities: I create a new activity diagram, add the necessary parameters which will be the inputs and outputs of the "process" represented by the activity. The are displayed on the left side of the diagram. I sometimes move them around a little bit when I want to connect them to an action or a fork. I always use either a port or a fork as a destination.

**Comment by danyeaw** [comment]
I tried out what is in #1441. I thought I would provide a bit more detail on how I would expect activities to work in general so that we can discuss the longer term vision of what we want to get to.

1. If you create a New Activity Diagram, it automatically nests it under an Activity. If you rename the Activity or the diagram, the name of both automatically change to match each other. You should be able to delete the diagram out of the activity if needed.
1. The activity the diagram is associated with should appear in the header for the modelElementName:
![image](https://user-images.githubusercontent.com/10014976/163689017-5fdd6647-17c7-495b-b641-a070335c39a6.png)
1. The representation of what is inside an Activity is shown in an Activity diagram. Viewing the "inside" of multiple activities on one diagram would be somewhat confusing.
1. If you add an Activity Parameter Node it gets added to the side of the diagram on the frame of the diagram, the frame adds padding to accommodate the parameter node:
![image](https://user-images.githubusercontent.com/10014976/163689079-6255bcc7-a503-4e30-9984-d2408027a634.png)
1. An action should be able to be a usage of an Activity with the "Name : Activity" syntax shown on the action. If there is a diagram nested in the defining Activity then there is the "trident" symbol shown on the action. If an action has a trident, you should be able to double click on it and open the Activity Diagram for it.
![image](https://user-images.githubusercontent.com/10014976/163689307-03d7fdd2-6047-4dbb-8f1e-ba737614f748.png)
1. Pins on the action correspond to the Activity Parameter Nodes of the Activity.

**Comment by amolenaar** [comment]
@danyeaw Each point is a feature in itself :wink:.

How do you differentiate between point 1. and 4.? In 1. the diagram sort of _is_ the activity, In 4. the activity is visible explicitly.

Points 5. and 6. are interesting, as they allow you use nest activities.

These could be nice improvements, but are any of them blocking for #1441?

**Comment by danyeaw** [comment]
> @danyeaw Each point is a feature in itself 😉.
Yup, I agree 👍 

> How do you differentiate between point 1. and 4.? In 1. the diagram sort of _is_ the activity, In 4. the activity is visible explicitly.
They are the same. For 1, the diagram is the view of the activity. For 4, you are able to add Activity Parameter Nodes to that view of the activity.

> These could be nice improvements, but are any of them blocking for https://github.com/gaphor/gaphor/pull/1441?
No, I don't think they block #1441, but I thought it would be worth discussing before merging.
